epochs: 100
batch_size: 2
lr: 0.001
device: 'cpu'  #'cuda' #
plot_opt: false
rescale_factor: 8 #10 #
blur_opt: True
nms_threshold: 0.075  #0.2
gamma: 0.75

data_path: PALA_data_InSilicoFlow/
ubx_dir: /storage/homefs/ch21z139/PALA_dataset/${data_path}
map_dir: /home/chris/LocalDatasets/03_PALA/${data_path}
data_dir: ${map_dir}
logging: False

# inference config
model_path: ./checkpoints/checkpoint_epoch100_5jan23.pth
save_opt: False