epochs: 100
batch_size: 2
lr: 0.001
device: 'cpu'  #'cuda' #
plot_opt: False
upscale_factor: 4 #8 #2 #10 #
rescale_factor: 10 #20
blur_opt: True
nms_threshold: 13 #20 #0.075  #0.2
gamma: 0.9
clutter_db: Null #-40
model: 'mspcn'  #'unet' #
avg_weight_opt: False
radial_sym_opt: False
rf_frame_opt: True
input_type: 'rf' #'iq' #

data_path: PALA_data_InSilicoFlow/
ubx_dir: /storage/homefs/ch21z139/PALA_dataset/${data_path}
map_dir: /home/chris/LocalDatasets/03_PALA/${data_path}
data_dir: ${map_dir}
logging: False

# inference config
model_path: Null
save_opt: False